Remove unused backend dependencies from toml file
vintasoftware/django-react-boilerplate pull request #659
Opened 2024-05-17 19:48 UTC by pamella

## Description

Remove unused backend dependencies from toml file

## Motivation and Context

## Screenshots (if appropriate):

## Steps to reproduce (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires documentation updates.
- [ ] I have updated the documentation accordingly.
- [X] My change requires dependencies updates.
- [X] I have updated the dependencies accordingly.

2024-05-19 13:41 UTC, fjsj commented on pyproject.toml
> -brotlipy = "^0.7.0"
Brotli was used by whitenoise indirectly.

2024-05-19 13:42 UTC, fjsj requested changes
Thanks. Please check comments.

2024-05-20 13:10 UTC, pamella commented on pyproject.toml
> -brotlipy = "^0.7.0"
Oh, all right, I reverted its removal. Thanks

2024-05-20 13:49 UTC, fjsj approved these changes

2024-05-20 13:49 UTC, merged